{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "1a49b3df",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from xgboost import XGBRegressor\n",
    "import seaborn as sns\n",
    "import matplotlib.pyplot as plt\n",
    "from sklearn.model_selection import KFold\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "from sklearn.model_selection import RandomizedSearchCV\n",
    "from sklearn.ensemble import GradientBoostingRegressor\n",
    "from mlxtend.regressor import StackingRegressor\n",
    "\n",
    "# Read data\n",
    "train = pd.read_csv('AmesHousing.csv')\n",
    "test = pd.read_csv('test.csv')\n",
    "train2 = pd.read_csv('train.csv')\n",
    "train.columns = train.columns.str.replace(' ', '')\n",
    "train = train.rename(columns = {\"YearRemod/Add\": \"YearRemodAdd\"}) # keep variables' name constant\n",
    "\n",
    "# Remove duplicates in data\n",
    "data = pd.concat([train,train2,test], axis = 0, sort = False)\n",
    "useless = ['Id','PID','Order','SalePrice'] \n",
    "data = data.drop(useless, axis = 1) # only keep features\n",
    "duplicate = data[data.duplicated(keep = 'last')].index\n",
    "duplicate = duplicate[0:390]\n",
    "train = train.drop(duplicate, axis = 0)\n",
    "training = pd.concat([train,train2], axis = 0, sort = False)\n",
    "useless = ['Id','PID','Order'] \n",
    "training = training.drop(useless, axis = 1) # final training dataset\n",
    "\n",
    "# Separating Target and Features\n",
    "target = training['SalePrice']\n",
    "test_id = test['Id']\n",
    "test = test.drop(['Id'],axis = 1)\n",
    "training2 = training.drop(['SalePrice'], axis = 1)\n",
    "\n",
    "# Concatenating train & test set\n",
    "train_test = pd.concat([training2,test], axis = 0, sort = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "5c3a465a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Converting non-numeric predictors stored as numbers into string\n",
    "train_test['MSSubClass'] = train_test['MSSubClass'].apply(str)\n",
    "train_test['YrSold'] = train_test['YrSold'].apply(str)\n",
    "train_test['MoSold'] = train_test['MoSold'].apply(str)\n",
    "train_test['OverallQual'] = train_test['OverallQual'].apply(str)\n",
    "train_test['OverallCond'] = train_test['OverallCond'].apply(str)\n",
    "\n",
    "# Fill missing values\n",
    "# Categorical features\n",
    "# Fill nan based on the description file \n",
    "train_test['Functional'] = train_test['Functional'].fillna('Typ')\n",
    "train_test['Electrical'] = train_test['Electrical'].fillna(\"SBrkr\")\n",
    "train_test['KitchenQual'] = train_test['KitchenQual'].fillna(\"TA\")\n",
    "\n",
    "# Fill nan with most frequnt class\n",
    "train_test['Exterior1st'] = train_test['Exterior1st'].fillna(train_test['Exterior1st'].mode()[0])\n",
    "train_test['Exterior2nd'] = train_test['Exterior2nd'].fillna(train_test['Exterior2nd'].mode()[0])\n",
    "train_test['SaleType'] = train_test['SaleType'].fillna(train_test['SaleType'].mode()[0])\n",
    "\n",
    "# Fill nan with none\n",
    "train_test[\"PoolQC\"] = train_test[\"PoolQC\"].fillna(\"None\")\n",
    "train_test[\"Alley\"] = train_test[\"Alley\"].fillna(\"None\")\n",
    "train_test['FireplaceQu'] = train_test['FireplaceQu'].fillna(\"None\")\n",
    "train_test['Fence'] = train_test['Fence'].fillna(\"None\")\n",
    "train_test['MiscFeature'] = train_test['MiscFeature'].fillna(\"None\")\n",
    "for col in ['GarageType', 'GarageFinish', 'GarageQual', 'GarageCond']:\n",
    "    train_test[col] = train_test[col].fillna('None')\n",
    "    \n",
    "for col in ('BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2'):\n",
    "    train_test[col] = train_test[col].fillna('None')\n",
    "    \n",
    "# Numeric features   \n",
    "# Fill nan with zero\n",
    "for col in ('GarageArea', 'GarageCars'):\n",
    "    train_test[col] = train_test[col].fillna(0)\n",
    "        \n",
    "for col in ('BsmtFinSF1', 'BsmtFinSF2', 'BsmtFullBath', 'BsmtHalfBath', 'MasVnrArea','BsmtUnfSF', 'TotalBsmtSF'):\n",
    "    train_test[col] = train_test[col].fillna(0)\n",
    "    \n",
    "# Fill nan with median vlues \n",
    "train_test['LotFrontage'] = train_test['LotFrontage'].fillna(train['LotFrontage'].median())\n",
    "\n",
    "# Add new features based on common knowledge\n",
    "train_test[\"SqFtPerRoom\"] = train_test[\"GrLivArea\"] / (train_test[\"TotRmsAbvGrd\"] +\n",
    "                                                       train_test[\"FullBath\"] +\n",
    "                                                       train_test[\"HalfBath\"] +\n",
    "                                                       train_test[\"KitchenAbvGr\"])\n",
    "\n",
    "train_test['Total_Home_Quality'] = train_test['OverallQual'] + train_test['OverallCond']\n",
    "\n",
    "train_test['Total_Bathrooms'] = (train_test['FullBath'] + (0.5 * train_test['HalfBath']) +\n",
    "                               train_test['BsmtFullBath'] + (0.5 * train_test['BsmtHalfBath']))\n",
    "\n",
    "train_test[\"HighQualSF\"] = train_test[\"1stFlrSF\"] + train_test[\"2ndFlrSF\"]\n",
    "train_test['renovated']=train_test['YearRemodAdd']+train_test['YearBuilt']\n",
    "\n",
    "# Removing the useless variables\n",
    "useless = ['GarageYrBlt','YearRemodAdd', \n",
    "    'MSSubClass', 'OverallCond', 'BsmtFinSF2', 'LowQualFinSF', 'BsmtHalfBath', \n",
    "    'KitchenAbvGr', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal', \n",
    "    'MoSold', 'YrSold'\n",
    "          ]\n",
    "train_test = train_test.drop(useless, axis = 1)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "aad6dc21",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Creating dummy variables from categorical features\n",
    "train_test_dummy = pd.get_dummies(train_test)\n",
    "\n",
    "from scipy.stats import skew\n",
    "numeric_features = train_test_dummy.dtypes[train_test_dummy.dtypes != object].index\n",
    "skewed_features = train_test_dummy[numeric_features].apply(lambda x: skew(x)).sort_values(ascending=False)\n",
    "high_skew = skewed_features[skewed_features > 0.5]\n",
    "skew_index = high_skew.index\n",
    "\n",
    "# Normalize skewed features using log_transformation\n",
    "for i in skew_index:\n",
    "    train_test_dummy[i] = np.log1p(train_test_dummy[i] )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "18014029",
   "metadata": {},
   "outputs": [],
   "source": [
    "# SalePrice after transformation\n",
    "target_log = np.log1p(target)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "91ad6533",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "final_train = train_test"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "99f2fbd5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Train-Test separation\n",
    "X_train = train_test_dummy[0:4000]\n",
    "X_test = train_test_dummy[4000:]\n",
    "\n",
    "# Creation of the RMSE metric:\n",
    "def rmse(y, y_pred):\n",
    "    return np.sqrt(mean_squared_error(y, y_pred))\n",
    "\n",
    "def cv_rmse(model):\n",
    "    rmse = np.sqrt(-cross_val_score(model, X_train, target_log, scoring = \"neg_mean_squared_error\", cv = kf))\n",
    "    return (rmse)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "9ff2e09e",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.0958417839320341\n",
      "0.019434673101199708\n",
      "     Id  SalePrice\n",
      "0  1461   112625.0\n",
      "1  1462   167654.0\n",
      "2  1463   191887.0\n",
      "3  1464   195845.0\n",
      "4  1465   179472.0\n"
     ]
    }
   ],
   "source": [
    "# XGB Regressor\n",
    "xgb = XGBRegressor()\n",
    "kf = KFold(n_splits = 10, random_state = 42, shuffle = True)\n",
    "score_xgb = cv_rmse(xgb)\n",
    "print(score_xgb.mean())\n",
    "print(score_xgb.std())\n",
    "\n",
    "# Train model\n",
    "submission = pd.read_csv(\"sample_submission.csv\")\n",
    "xgb_model = xgb.fit(X_train, target_log)\n",
    "submission.iloc[:,1] = np.floor(np.expm1(xgb_model.predict(X_test)))\n",
    "print(submission.head())\n",
    "#submission.to_csv(\"xgb_oliver_08041414.csv\", index = False)\n",
    "#0.09156863522810113\n",
    "#0.1230436287439903"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 32,
   "id": "5629ba8e",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.11751871948356322\n",
      "0.018568192159422837\n",
      "     Id  SalePrice\n",
      "0  1461   120990.0\n",
      "1  1462   149303.0\n",
      "2  1463   184874.0\n",
      "3  1464   189845.0\n",
      "4  1465   184477.0\n",
      "Fitting 5 folds for each of 250 candidates, totalling 1250 fits\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py\", line 593, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 448, in fit\n",
      "    self._check_params()\n",
      "  File \"/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/ensemble/_gb.py\", line 270, in _check_params\n",
      "    raise ValueError(\"alpha must be in (0.0, 1.0) but \"\n",
      "ValueError: alpha must be in (0.0, 1.0) but was 1.0\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/oliver/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_search.py:918: UserWarning: One or more of the test scores are non-finite: [-0.00771953 -0.00975835         nan -0.00806392 -0.00730334 -0.00961759\n",
      " -0.00688862         nan -0.00717064 -0.03160628         nan -0.00790577\n",
      " -0.00833429 -0.00718154 -0.01661126 -0.00743959         nan -0.03154887\n",
      " -0.00739908 -0.00690504 -0.0075319  -0.00780335 -0.00668666         nan\n",
      " -0.00920041 -0.01357331 -0.00733614 -0.00776423         nan -0.00685743\n",
      " -0.01053666 -0.00878464 -0.01036785 -0.00677357         nan -0.00873682\n",
      " -0.00842461 -0.01334626 -0.03834282         nan -0.00710502 -0.0109084\n",
      " -0.0089034  -0.00727843 -0.00876808 -0.00845619 -0.0079428  -0.01683092\n",
      " -0.00910902 -0.01468577 -0.00719316 -0.03944658 -0.00730015 -0.05308384\n",
      " -0.00800307 -0.00705548 -0.00731985 -0.00843967 -0.00802064 -0.0088864\n",
      " -0.00767678 -0.01478351 -0.0091095  -0.00752886 -0.00758612 -0.00708227\n",
      " -0.00898433 -0.01444096         nan -0.00818041 -0.00959875         nan\n",
      " -0.0170198  -0.00982011 -0.00897341         nan -0.00702956 -0.0068419\n",
      " -0.03504713 -0.00755432 -0.00724422 -0.03822194 -0.00737757 -0.00790661\n",
      " -0.05277997 -0.00766203 -0.00927649 -0.00733216         nan -0.03156584\n",
      "         nan -0.00659589 -0.03486839         nan -0.00843185 -0.00744798\n",
      " -0.00747731 -0.01002465 -0.05306293 -0.03148399 -0.00907926 -0.01066663\n",
      " -0.00736692 -0.01034106 -0.00800987         nan -0.00787631 -0.01399325\n",
      "         nan -0.00780658 -0.01128866 -0.00744972 -0.01703728 -0.00884263\n",
      " -0.01031054 -0.00701588 -0.00701479 -0.01360868 -0.01686277 -0.01075379\n",
      "         nan -0.00849017 -0.00910244 -0.01080308 -0.01677484 -0.00817286\n",
      " -0.01715698 -0.00971365 -0.00876134 -0.03831364 -0.01357868 -0.00832544\n",
      " -0.00787346 -0.00747226 -0.00713329 -0.00742819 -0.0088556  -0.00736632\n",
      " -0.01682106 -0.00954449 -0.00750273 -0.05284521 -0.016961   -0.00734662\n",
      " -0.00993521 -0.05287756 -0.00872839 -0.01051711 -0.01131276 -0.00783835\n",
      " -0.00742931 -0.03950692 -0.01333715 -0.00793309         nan -0.00744899\n",
      " -0.01343924 -0.0078556  -0.00897941 -0.01110997 -0.00760666 -0.01089984\n",
      "         nan -0.00678527 -0.00756264         nan -0.01764994 -0.01152452\n",
      " -0.00866648 -0.00929251 -0.00833229 -0.00668305 -0.00953654 -0.00972583\n",
      " -0.00832719 -0.01746913 -0.00781701 -0.01080481 -0.00741983         nan\n",
      " -0.0077331  -0.00683704 -0.00753835 -0.00911917 -0.00874686 -0.00792928\n",
      " -0.01675472 -0.01081177 -0.00779514 -0.01396735 -0.05278673         nan\n",
      " -0.01407406 -0.00680591 -0.00780832 -0.0075429  -0.03973156 -0.00786318\n",
      " -0.03966615 -0.00800049 -0.00711188 -0.00836677 -0.00734651 -0.01037335\n",
      " -0.01112096 -0.00708096 -0.00969817 -0.01432373 -0.01406785 -0.00753284\n",
      " -0.00969001 -0.01040176 -0.007689   -0.00834301 -0.03842424 -0.00996658\n",
      " -0.00816701 -0.00820348 -0.00679164         nan -0.00752838 -0.00745567\n",
      " -0.01336583 -0.00964632 -0.00844723 -0.00764237 -0.03163226 -0.00709261\n",
      " -0.00840185 -0.01345782 -0.0174322  -0.0070345  -0.01478297 -0.00996612\n",
      " -0.0169005  -0.0107742  -0.00701985 -0.00741642 -0.03154442 -0.00726633\n",
      " -0.01676464 -0.03822211 -0.00742097 -0.00800611         nan -0.00708641\n",
      " -0.0077795  -0.00692784 -0.01732837 -0.01342725]\n",
      "  warnings.warn(\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best parameters: {'subsample': 0.3, 'n_estimators': 500, 'max_depth': 10, 'learning_rate': 0.05, 'alpha': 0.0001}\n",
      "Lowest RMSE:  0.08121510953385991\n",
      "     Id  SalePrice\n",
      "0  1461   107094.0\n",
      "1  1462   169194.0\n",
      "2  1463   187310.0\n",
      "3  1464   192961.0\n",
      "4  1465   188426.0\n"
     ]
    }
   ],
   "source": [
    "# Gradient Boosting\n",
    "gradientboost = GradientBoostingRegressor()\n",
    "kf = KFold(n_splits = 10, random_state = 42, shuffle = True)\n",
    "score_gradientboost = cv_rmse(gradientboost)\n",
    "print(score_gradientboost.mean())\n",
    "print(score_gradientboost.std())\n",
    "\n",
    "# Train model\n",
    "submission = pd.read_csv(\"sample_submission.csv\")\n",
    "gradientboost_model = gradientboost.fit(X_train, target_log)\n",
    "submission.iloc[:,1] = np.floor(np.expm1(gradientboost_model.predict(X_test)))\n",
    "print(submission.head())\n",
    "#submission.to_csv(\"oliver_08061722_gradientboost.csv\", index = False)\n",
    "\n",
    "# RandomizedSearch to improve model\n",
    "para_grid = { 'max_depth': [3,6,10], 'learning_rate': [0.01, 0.05, 0.1],\n",
    "           'n_estimators': [100, 500, 1000], 'subsample': [0.3, 0.7], 'alpha': np.logspace(-9, 0, 10)}\n",
    "grid_search_gradientboost = RandomizedSearchCV(gradientboost, para_grid, scoring = 'neg_mean_squared_error', n_iter = 250, verbose = 1)\n",
    "grid_search_gradientboost.fit(X_train, target_log)\n",
    "print(\"Best parameters:\", grid_search_gradientboost.best_params_)\n",
    "print(\"Lowest RMSE: \", (-grid_search_gradientboost.best_score_)**(1/2.0))\n",
    "submission.iloc[:,1] = np.floor(np.expm1(grid_search_gradientboost.predict(X_test)))\n",
    "print(submission.head())\n",
    "submission.to_csv(\"oliver_08061722_gradientboost.csv\", index = False)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "7325adef",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting 5 folds for each of 25 candidates, totalling 125 fits\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "RandomizedSearchCV(estimator=XGBRegressor(base_score=None, booster=None,\n",
       "                                          colsample_bylevel=None,\n",
       "                                          colsample_bynode=None,\n",
       "                                          colsample_bytree=None, gamma=None,\n",
       "                                          gpu_id=None, importance_type='gain',\n",
       "                                          interaction_constraints=None,\n",
       "                                          learning_rate=None,\n",
       "                                          max_delta_step=None, max_depth=None,\n",
       "                                          min_child_weight=None, missing=nan,\n",
       "                                          monotone_constraints=None,\n",
       "                                          n_estimators=100, n_jobs...\n",
       "       6.13590727e+06, 7.39072203e+06, 8.90215085e+06, 1.07226722e+07,\n",
       "       1.29154967e+07, 1.55567614e+07, 1.87381742e+07, 2.25701972e+07,\n",
       "       2.71858824e+07, 3.27454916e+07, 3.94420606e+07, 4.75081016e+07,\n",
       "       5.72236766e+07, 6.89261210e+07, 8.30217568e+07, 1.00000000e+08]),\n",
       "                                        'colsample_bytree': [0.3, 0.7],\n",
       "                                        'learning_rate': [0.01, 0.05, 0.1],\n",
       "                                        'max_depth': [3, 6, 10],\n",
       "                                        'n_estimators': [100, 500, 1000]},\n",
       "                   scoring='neg_mean_squared_error', verbose=1)"
      ]
     },
     "execution_count": 28,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# GridSearch/RandomizedSearch to improve the model\n",
    "para_grid = { 'max_depth': [3,6,10], 'learning_rate': [0.01, 0.05, 0.1],\n",
    "           'n_estimators': [100, 500, 1000], 'colsample_bytree': [0.3, 0.7], 'alpha': np.logspace(0, 8, 100)}\n",
    "xgb = XGBRegressor()\n",
    "#grid_search_xgb = GridSearchCV(xgb, para_grid, cv = 5, scoring = 'neg_mean_squared_error')\n",
    "#grid_search_xgb = RandomizedSearchCV(xgb, para_grid, scoring = 'neg_mean_squared_error', n_iter = 250, verbose = 1)\n",
    "grid_search_xgb = RandomizedSearchCV(xgb, para_grid, scoring = 'neg_mean_squared_error', n_iter = 250, verbose = 1)\n",
    "grid_search_xgb.fit(X_train, target_log)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "9845064d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Best parameters: {'n_estimators': 1000, 'max_depth': 10, 'learning_rate': 0.1, 'colsample_bytree': 0.7, 'alpha': 13.530477745798075}\n",
      "Lowest RMSE:  0.1230436287439903\n",
      "     Id  SalePrice\n",
      "0  1461   119191.0\n",
      "1  1462   154002.0\n",
      "2  1463   196317.0\n",
      "3  1464   196199.0\n",
      "4  1465   181732.0\n"
     ]
    }
   ],
   "source": [
    "print(\"Best parameters:\", grid_search_xgb.best_params_)\n",
    "print(\"Lowest RMSE: \", (-grid_search_xgb.best_score_)**(1/2.0))\n",
    "submission.iloc[:,1] = np.floor(np.expm1(grid_search_xgb.predict(X_test)))\n",
    "print(submission.head())\n",
    "#submission.to_csv(\"xgb_oliver_08051226.csv\", index = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "12456eaf",
   "metadata": {
    "scrolled": true
   },
   "outputs": [],
   "source": [
    "stack = StackingRegressor(regressors = (XGBRegressor(n_estimators = 1000, max_depth = 10, learning_rate = 0.1, colsample_bytree = 0.7, alpha = 13.530477745798075), \n",
    "                                        GradientBoostingRegressor(subsample = 0.3, n_estimators = 500, max_depth = 10, learning_rate = 0.05, alpha = 0.0001)), \n",
    "                          meta_regressor = XGBRegressor(), \n",
    "                          use_features_in_secondary = True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "eb06118f",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "0.08703126483397647\n",
      "0.020400837690123658\n"
     ]
    }
   ],
   "source": [
    "stack_score = cv_rmse(stack)\n",
    "print(stack_score.mean())\n",
    "print(stack_score.std())\n",
    "# 0.08279143055492903\n",
    "# 0.01901712515315616"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "bdc5fff9",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting 5 folds for each of 250 candidates, totalling 1250 fits\n",
      "     Id  SalePrice\n",
      "0  1461   107795.0\n",
      "1  1462   167184.0\n",
      "2  1463   191392.0\n",
      "3  1464   192861.0\n",
      "4  1465   186055.0\n"
     ]
    }
   ],
   "source": [
    "# Train model\n",
    "submission = pd.read_csv(\"sample_submission.csv\")\n",
    "#stack_model = stack.fit(X_train, target_log)\n",
    "#submission.to_csv(\"oliver_08281253_stack.csv\", index = False)\n",
    "\n",
    "# GridSearch/RandomizedSearch to improve the model\n",
    "para_grid = { 'meta_regressor__max_depth': [3,6,10], 'meta_regressor__learning_rate': [0.01, 0.05, 0.1],\n",
    "           'meta_regressor__n_estimators': [100, 500, 1000], 'meta_regressor__colsample_bytree': [0.3, 0.7], 'meta_regressor__alpha': np.logspace(0, 8, 100)}\n",
    "#stack = XGBRegressor()\n",
    "grid_search_stack = RandomizedSearchCV(stack, para_grid, scoring = 'neg_mean_squared_error', n_iter = 250, verbose = 1)\n",
    "grid_search_stack.fit(X_train, target_log)\n",
    "submission.iloc[:,1] = np.floor(np.expm1(grid_search_stack.predict(X_test)))\n",
    "print(submission.head())\n",
    "#submission.to_csv(\"oliver_08281257_stack.csv\", index = False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "7e00e6d1",
   "metadata": {},
   "outputs": [],
   "source": [
    "submission.to_csv(\"oliver_08281831_stack.csv\", index = False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
